# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cron_beat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='beat date')),
                ('total_flow', models.BigIntegerField(default=0)),
                ('beat_date_flow', models.BigIntegerField(default=0)),
            ],
        ),
    ]
