# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=4)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 16, 21, 53, 762584, tzinfo=utc), verbose_name='order date')),
                ('valid_date', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 16, 21, 53, 762629, tzinfo=utc), verbose_name='valid_date')),
                ('dead_date', models.DateTimeField(default=datetime.datetime(2017, 11, 24, 16, 21, 53, 762673, tzinfo=utc), verbose_name='daed_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
