# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20171125_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_order',
            name='dead_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='daed_date'),
        ),
        migrations.AlterField(
            model_name='history_order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='history_order',
            name='valid_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='valid_date'),
        ),
    ]
