# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20171125_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(max_length=32)),
                ('user', models.CharField(default=None, max_length=256)),
                ('activate_time_stamp', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
    ]
