# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation_code',
            name='plan',
            field=models.CharField(default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='activation_code',
            name='user',
            field=models.CharField(default='', max_length=256),
        ),
    ]
