# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20180118_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=32)),
                ('money', models.IntegerField(default=0)),
                ('username', models.CharField(default='', max_length=256)),
                ('payconfirm', models.BooleanField(default=False)),
                ('payChannel', models.CharField(max_length=32)),
            ],
        ),
    ]
