# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_full', models.CharField(max_length=255, unique=True)),
                ('ip', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=32)),
                ('request', models.CharField(max_length=320)),
                ('useragent', models.CharField(max_length=500)),
            ],
        ),
    ]
